version: 1.0.{build}
image: Ubuntu
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  - sh: dotnet tool install --global dotnet-sonarscanner
before_build:
  - sh: dotnet sonarscanner begin /k:mickaelseban_BasicWrapperTool /v:$APPVEYOR_BUILD_VERSION /o:mickaelseban /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=6eea5d195976578b5f56f6bcbb81be4004fe83c1 /d:sonar.coverage.exclusions="tests/*Tests/**" /d:sonar.cs.opencover.reportsPaths="*.opencover.xml"
build_script:
  - sh: dotnet restore BasicWrapperTool.sln --no-cache
  - sh: dotnet build BasicWrapperTool.sln --no-restore
test_script:
  - sh: dotnet test test/BasicWrapperTool.Tests --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput=../../tests-coverage
after_test:
  - sh: dotnet sonarscanner end /d:sonar.login=6eea5d195976578b5f56f6bcbb81be4004fe83c1
artifacts:
- path: '**/*.nupkg'
  name: NuGetPackages
deploy:
- provider: NuGet
  api_key:
    secure: oy2bqkyc2gtxwdazrnaadpvo3dvc7veuvklsjz322bm3ba
  skip_symbols: false
  symbol_server: https://nuget.smbsrc.net/
  artifact: /.*\.nupkg/
  on:
    branch: master
notifications:
- provider: Email
  to:
  - seban99@hotmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false